# Generated by Django 3.1 on 2021-05-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210510_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
    ]
