# Generated by Django 3.1 on 2021-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='activation_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
